### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m1-evaluacion-intermedia-laurapareja#1]
Really cool job @laurapareja  !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Fix the language of the page

## CSS - box model
- [x] Instead of adding extra space at the bottom of the header, you can make the menu links taller, that would make the header be tall enough and also would make the link easier to touch on mobile devices ;)
- [x] Your `main` element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using min-height to do the trick ;)

## CSS - other
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Finish the main title styles: words should jump and the typography is bolder
- [x] Fix color of links and main title size.

## Assets
- [x] Use relative routes like `./style/style.css`.
- [x] Move the logo to images folder.

## Good practices
- [x] Organize your files in folders, you have a guide to help you with that here --> https:## books.adalab.es/materiales-front-end-f/modulo-1.-hola-mundo/1_1_intro_a_la_web#notas-finales-sobre-como-organizar-nuestro-proyecto

## Final remarks

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with main content.

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
Muy buen ejercicio Laura sigue así, estoy muy contento!!!
![Good job](https://media.giphy.com/media/Hc8PMCBjo9BXa/giphy.gif)

**Comment by laurapareja** [comment]
He subido los cambios y también he puesto el logo clickable. 

Muchas gracias :).

**Comment by migueldelmazo** [comment]
Gracias por hacer las mejoras que os hemos pedido!!!
